### ISSUE TITLE
AutocompletePrediction secondaryText missing

### ISSUE THREAD

**Issue by onurh** [mohammadkamal/google_places#5]
There is a mapping issue on secondaryText when using autocomplete. 

> flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: type 'Null' is not a subtype of type 'String'
flutter: 
#0      new AutocompletePrediction.fromJson (package:google_places_sdk/src/models/autocomplete_prediction.dart:52:26)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#3      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#4      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#5      new List.of (dart:core-patch/array_patch.dart:39:18)
#6      ListIterable.toList (dart:_internal/iterable.dart:224:7)
#7      MethodChannelGooglePlaces.getAutoCompletePredictions (package:google_places_sdk/src/google_places_method_channel.dart:85:57)
<asynchronous suspension>

**Comment by mohammadkamal** [comment]
@onurh I will work on it. Thank you.

**Comment by mohammadkamal** [comment]
Added the null operator in the latest version.

Thank you for notifying me.
